// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("CSharp.Formatting")>]
[<assembly: AssemblyProductAttribute("CSharp.Formatting")>]
[<assembly: AssemblyDescriptionAttribute("Tools for generating C# web documentation")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "CSharp.Formatting"
    let [<Literal>] AssemblyProduct = "CSharp.Formatting"
    let [<Literal>] AssemblyDescription = "Tools for generating C# web documentation"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
