// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("CSharp.Formatting")>]
[<assembly: AssemblyProductAttribute("CSharp.Formatting")>]
[<assembly: AssemblyDescriptionAttribute("Tools for generating C# web documentation")>]
[<assembly: AssemblyVersionAttribute("0.2.2")>]
[<assembly: AssemblyFileVersionAttribute("0.2.2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "CSharp.Formatting"
    let [<Literal>] AssemblyProduct = "CSharp.Formatting"
    let [<Literal>] AssemblyDescription = "Tools for generating C# web documentation"
    let [<Literal>] AssemblyVersion = "0.2.2"
    let [<Literal>] AssemblyFileVersion = "0.2.2"
